### PR TITLE
sendByTemplate : must now specify fromMail adress

### PR DESCRIPTION
**Pull request by lecajer**

### CODE REVIEW

**Comment by lecajer** [comment]
@ngroot we needed different senders not sure this is the right way to do so. @mmstanislas tried to overwride the config in $app...

Cheers

**Comment by ngroot** [comment]
@Jeremlicious you are missing files in the PR. I think you should also put the fromEmail param at the end.

Please see: https://github.com/CrazyAwesomeCompany/ESP/blob/master/lib/CAC/Component/ESP/Adapter/Engine/EngineMail.php#L82-L87

It is grabbing the fromEmail from the options array. If you change this function by adding an optional parameter at the end with the fromEmail that will overwrite the options value when given you are there. Adding it as first parameter requires you to always give it when calling the function.

**Comment by lecajer** [comment]
Ok @ngroot we are now passing the fromEmail in the table $params
So it is backward compatible

**Comment by lecajer** [comment]
No it's not actually :D
 we made the change in our api

**Pull request merged**
